const ActionType = {
    UPDATE_USER: 'UPDATE_USER',
    GET_USER: 'GET_USER',
    ADD_USER: 'ADD_USER',
    DEL_USER: 'DEL_USER',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    GET_PRODUCT: 'GET_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    DEL_PRODUCT: 'DEL_PRODUCT'
}

export default ActionType